# Generated by Django 2.1.3 on 2018-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='output',
            field=models.CharField(blank=True, max_length=81, null=True),
        ),
    ]
