# Generated by Django 2.1.3 on 2018-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_solver', '0002_auto_20181119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
