# Generated by Django 2.1.3 on 2018-11-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_solver', '0003_auto_20181120_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
